import type { ErrorCodeRegistry } from "@/types"

export const errorCodes: ErrorCodeRegistry[] = 
[
  {
    "code": "ERR-1-30001-001",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "NIR absent",
    "causePossible": "• Saisie manquante\n• Champ NIR non renseigné à l'embauche\n• Oubli lors de la création de la fiche salarié dans le SIRH\n• Salarié étranger en attente d'attribution de NIR définitif\n• Perte du champ lors de l'export DSN",
    "solution": "• Renseigner le NIR du salarié\n• Demander la carte Vitale ou l'attestation de sécurité sociale\n• Utiliser un NIR provisoire (technique) en attendant le NIR définitif puis régulariser\n• Corriger le mapping d'export si le champ existe en base mais n'est pas transmis",
    "responsable": "• RH\n• SIRH/IT\n• Salarié",
    "exemple": "• (vide)\n• null\n• chaîne vide \"\"",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-001",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30001-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "NIR contient caractères non numériques",
    "causePossible": "• Saisie erronée avec lettres/symboles\n• Erreur de frappe lors de la saisie manuelle\n• Copier-coller depuis un document contenant des caractères parasites\n• Confusion avec un autre identifiant (matricule, numéro de sécurité sociale provisoire)",
    "solution": "• Supprimer caractères non numériques\n• Corriger le NIR à partir de la carte Vitale\n• Vérifier auprès du salarié le numéro exact\n• Nettoyer automatiquement le champ dans le pipeline d'import",
    "responsable": "• RH\n• G2S Cortex",
    "exemple": "• ABC123456789012\n• 1 85 05 78 006 084*12\n• NIR avec espaces ou tirets non nettoyés",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-002",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30001-003",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "NIR longueur incorrecte",
    "causePossible": "• Saisie incomplète ou trop longue\n• Troncature lors de l'export SIRH vers DSN\n• Chiffre oublié ou dupliqué lors de la saisie manuelle\n• Clé de contrôle non incluse ou incluse par erreur dans le champ NIR",
    "solution": "• Corriger la longueur selon la norme NIR (13 chiffres + 2 chiffres de clé)\n• Vérifier le NIR complet sur la carte Vitale\n• Recomposer le NIR avec sa clé de contrôle\n• Corriger le mapping d'export si troncature systématique",
    "responsable": "• RH\n• SIRH/IT",
    "exemple": "• 123456789012\n• 12345678901234567\n• 1850578006084",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-003",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30001-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "Clé de contrôle invalide mais autres identifiants concordent",
    "causePossible": "• Erreur de saisie isolée\n• Inversion de deux chiffres lors de la saisie\n• Faute de frappe unique n'affectant pas la clé mod97\n• Ancien NIR conservé après une correction partielle",
    "solution": "• Vérifier et corriger la clé ou valider via matricule/nom\n• Recalculer la clé de contrôle mod97\n• Confirmer l'identité via une autre pièce justificative\n• Mettre à jour le NIR dans le SIRH puis régénérer la DSN",
    "responsable": "• RH",
    "exemple": "• clé mod97 invalide\n• 1 85 05 78 006 084 88 (clé erronée)",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30001-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30001-004",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "Clé de contrôle invalide et aucune autre identification concordante",
    "causePossible": "• NIR incorrect ou usurpation\n• Erreur de saisie multiple rendant le NIR totalement invalide\n• Utilisation du NIR d'une autre personne par erreur\n• Fraude ou usurpation d'identité à vérifier",
    "solution": "• Demander la vérification RH et corriger\n• Exiger un justificatif d'identité et la carte Vitale\n• Signaler le cas à la CNAV/CPAM si suspicion de fraude\n• Bloquer la DSN jusqu'à régularisation du NIR",
    "responsable": "• RH\n• Service juridique",
    "exemple": "• clé mod97 invalide et pas de concordance\n• NIR appartenant à un autre salarié du groupe",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-004",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30001-005",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "Le code Python d'extraction ne garde que les valeurs par défaut.(000... )",
    "causePossible": "• Valeur par défaut ou export erroné\n• Le code Python d'extraction ne garde que les valeurs par défaut (000...)\n• Champ NIR non mappé correctement dans le pipeline d'extraction\n• Valeur null convertie en zéros par le pipeline",
    "solution": "• Remplacer par le NIR réel\n• Corriger le bug du pipeline Python d'extraction\n• Revérifier le mapping source/cible du champ NIR\n• Relancer l'extraction après correction du pipeline",
    "responsable": "• G2S Cortex\n• RH",
    "exemple": "• 000000000000000\n• 0000000000000\n• 999999999999999",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-005",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30001-006",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "NIR dupliqué pour plusieurs individus distincts",
    "causePossible": "• Doublon d'enregistrement ou mauvaise attribution\n• Création de deux fiches salarié pour la même personne\n• Erreur de recopie du NIR d'un collègue\n• Fusion de bases SIRH ayant généré des doublons",
    "solution": "• Vérifier les fiches et corriger les NIR/affectations\n• Fusionner les fiches salarié en doublon\n• Contacter les salariés concernés pour confirmer leur NIR réel\n• Mettre en place un contrôle d'unicité du NIR dans le SIRH",
    "responsable": "• RH\n• SIRH/IT",
    "exemple": "• même NIR pour 2 matricules\n• même NIR pour un salarié actif et un salarié sorti",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30001-006",
    "familleInes": "Salarié",
    "prioriteInes": "P1",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30001-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30001",
    "nom": "NIR",
    "description": "NIR incohérent avec le sexe/date de naissance (vérifier)",
    "causePossible": "• Erreur de saisie partielle ou inversion de chiffres\n• NIR incohérent avec le sexe/date de naissance (vérifier)\n• Changement de sexe à l'état civil non répercuté sur le NIR\n• Faute de frappe sur le premier chiffre (1/2) ou sur les chiffres de l'année de naissance",
    "solution": "• Vérifier la fiche salarié et corriger si nécessaire\n• Confirmer le NIR via la carte Vitale\n• Corriger le sexe ou la date de naissance selon le cas erroné\n• Ne pas modifier si le NIR est confirmé exact malgré l'apparente incohérence",
    "responsable": "• RH\n• Salarié",
    "exemple": "• NIR indique sexe opposé\n• NIR indique une année de naissance différente du dossier",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "NIR absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30001-002",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30019-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30019",
    "nom": "Matricule",
    "description": "Matricule incohérent avec référentiel",
    "causePossible": "• Incohérence entre DSN et dossier RH\n• Renumérotation du matricule non répercutée dans tous les systèmes\n• Erreur de saisie du matricule dans le SIRH\n• Changement de matricule lors d'un transfert d'établissement",
    "solution": "• Vérifier le matricule dans le référentiel salarié\n• Harmoniser le matricule entre le SIRH et la paie\n• Mettre à jour le référentiel après un changement de matricule\n• Corriger la saisie erronée",
    "responsable": "• RH\n• SIRH/IT",
    "exemple": "• 009221\n• matricule avec un chiffre en trop\n• ancien matricule conservé après renumérotation",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_WRN-2-30019-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-2-30019-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30019",
    "nom": "Matricule",
    "description": "Matricule vide",
    "causePossible": "• Problème au niveau du pipeline d'extraction\n• Champ matricule non mappé lors de l'export DSN\n• Erreur de jointure entre les tables source dans le pipeline Python\n• Matricule supprimé par erreur lors d'un nettoyage de données",
    "solution": "• Vérifier le matricule dans le référentiel salarié\n• Corriger le pipeline d'extraction Python\n• Revérifier la jointure des données source\n• Relancer l'extraction après correction",
    "responsable": "• G2S Cortex",
    "exemple": "• (vide)\n• null\n• chaîne vide \"\"",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_ERR-2-30019-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-05005-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "5005",
    "nom": "Declaration.Mois",
    "description": "Mois hors période attendue",
    "causePossible": "• Période de déclaration ne correspond pas aux dates d'arrêt\n• Erreur de saisie du mois de déclaration\n• Mois DSN non actualisé après un changement de la nomenclature mensuelle\n• Déclaration tardive rattachée au mauvais mois",
    "solution": "• Vérifier la période déclarée contre les dates du dossier\n• Corriger le mois de déclaration\n• Effectuer une déclaration corrective sur la bonne période\n• Contrôler le paramétrage des mois DSN dans le pipeline",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 01/13/2026\n• 00/2026\n• mois 00 ou 13 inexistant",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Mois de déclaration incohérent avec les dates d'arrêt",
    "codeInes": "INES_IJSS_WRN-2-05005-001",
    "familleInes": "DSN",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-05005-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "5005",
    "nom": "Declaration.Mois",
    "description": "Mois incompatible avec les dates d’arrêt",
    "causePossible": "• La déclaration de mois ne recouvre pas les journées d'arrêt\n• Arrêt à cheval sur deux mois déclaré sur un seul mois\n• Erreur de report du mois lors d'une régularisation\n• Décalage entre la date de saisie et la date réelle de l'arrêt",
    "solution": "• Corriger le mois de déclaration ou ajuster les dates d'arrêt\n• Répartir l'arrêt sur les mois concernés si à cheval\n• Vérifier la cohérence entre le mois DSN et les dates du certificat médical\n• Effectuer une déclaration corrective",
    "responsable": "• Paie",
    "exemple": "• 01/02/2026\n• arrêt du 25/01 au 05/02 déclaré uniquement en janvier",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Mois de déclaration incohérent avec les dates d'arrêt",
    "codeInes": "INES_IJSS_WRN-2-05005-002",
    "familleInes": "DSN",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "ERR-1-30002-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30002",
    "nom": "NomFamille",
    "description": "Nom de famille contient éléments invalides",
    "causePossible": "• Caractères numériques ou ponctuation non autorisée\n• Faute de frappe lors de la saisie manuelle\n• Copier-coller depuis un document contenant des caractères parasites\n• Erreur d'encodage lors de l'import de données",
    "solution": "• Nettoyer le nom des caractères invalides\n• Corriger la saisie à partir de la pièce d'identité\n• Vérifier l'encodage du fichier source lors de l'import\n• Ajouter un contrôle de saisie dans le SIRH",
    "responsable": "• RH\n• G2S Cortex",
    "exemple": "• C0VINDASSAMY\n• COVINDASSAMY123\n• COVINDASSAMY;\n• COVINDASSAMY#",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nom de famille absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30002-002",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30002-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30002",
    "nom": "NomFamille",
    "description": "Nom de famille différent du référentiel",
    "causePossible": "• Incohérence orthographique ou d'usage\n• Faute de frappe lors de la saisie d'un des deux systèmes\n• Nom mal transcrit depuis un document étranger\n• Changement de nom (mariage) non répercuté partout",
    "solution": "• Comparer avec le dossier RH et harmoniser\n• Corriger l'orthographe selon la pièce d'identité\n• Mettre à jour le nom dans tous les systèmes après un changement d'état civil\n• Vérifier la source de la divergence (SIRH vs export DSN)",
    "responsable": "• RH",
    "exemple": "• COVINDASSAMY / COVINDASSAMI\n• MARTIN / MARTINE\n• nom avec ou sans tiret",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nom de famille absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30002-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30003-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30003",
    "nom": "NomUsage",
    "description": "Nom d’usage différent du nom de naissance",
    "causePossible": "• Nom d'usage déclaré sans cohérence\n• Nom d'usage saisi par erreur à la place du nom de naissance\n• Changement de nom d'usage (mariage, divorce) non mis à jour\n• Confusion entre nom de naissance et nom d'usage lors de la saisie",
    "solution": "• Vérifier l'usage réel du salarié\n• Confirmer le nom d'usage souhaité par le salarié\n• Corriger le champ concerné selon la pièce d'identité\n• Mettre à jour après un changement de situation familiale",
    "responsable": "• RH\n• Salarié",
    "exemple": "• KAMMERER\n• nom d'usage identique au nom de naissance alors que différent attendu\n• nom d'usage d'un ex-conjoint conservé par erreur",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Nom de famille absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30003-002",
    "familleInes": "Salarié",
    "prioriteInes": "P3",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30003-001",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30003",
    "nom": "NomUsage",
    "description": "Nom d’usage mal formaté",
    "causePossible": "• Caractères invalides ou libellé trop long\n• Faute de frappe ou caractère spécial ajouté par erreur\n• Nom d'usage composé mal formaté (espaces, tirets)\n• Export tronqué ou corrompu",
    "solution": "• Corriger le format du nom d'usage\n• Nettoyer les caractères invalides\n• Standardiser le format selon la norme DSN\n• Corriger le pipeline d'export si le problème est systématique",
    "responsable": "• G2S Cortex\n• RH",
    "exemple": "• KAMMERER*\n• KAMMERER-DUPONT-MARTIN-DURAND (trop long)\n• KAMMERER;",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nom de famille absent, invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30003-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-1-30004-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "30004",
    "nom": "Prenoms",
    "description": "Prénoms contient caractères invalides",
    "causePossible": "• Caractères numériques ou symboles non autorisés\n• Faute de frappe lors de la saisie manuelle\n• Prénom d'origine étrangère mal translittéré avec des symboles\n• Erreur d'encodage lors de l'import",
    "solution": "• Nettoyer le champ prénom\n• Corriger la saisie à partir de la pièce d'identité\n• Vérifier l'encodage du fichier source\n• Standardiser la translittération des prénoms étrangers",
    "responsable": "• G2S Cortex\n• RH",
    "exemple": "• Thi-bach-tuyêt#\n• Jean123\n• Marie@",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Prénom ou sexe invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-30004-002",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30004-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30004",
    "nom": "Prenoms",
    "description": "Prénoms incohérents avec le dossier salarié",
    "causePossible": "• Différence d'orthographe ou d'ordre des prénoms\n• Prénoms composés saisis dans un ordre différent selon le système\n• Faute de frappe dans un des deux systèmes\n• Accents ou tirets non harmonisés entre le SIRH et l'export DSN",
    "solution": "• Harmoniser le prénom avec le dossier RH\n• Corriger l'orthographe selon la pièce d'identité\n• Aligner l'ordre des prénoms composés entre les systèmes\n• Uniformiser les accents et la ponctuation",
    "responsable": "• RH",
    "exemple": "• Thi-bach-tuyêt / Thi Bach Tuyet\n• Jean-Pierre / Pierre-Jean\n• Marie-Claire / Marie Claire",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Prénom ou sexe invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30004-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-2-40003-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40003",
    "nom": "StatutRC_Libelle",
    "description": "Libellé statut RC inconnu",
    "causePossible": "• Valeur hors référentiel DSN\n• Libellé métier interne non traduit en nomenclature DSN\n• Faute de frappe dans le libellé\n• Ancienne codification de statut non mise à jour",
    "solution": "• Utiliser un statut RC reconnu\n• Consulter la nomenclature DSN des statuts de retraite complémentaire\n• Corriger le mapping SIRH vers DSN\n• Mettre à jour le référentiel des statuts RC",
    "responsable": "• Paie\n• SIRH/IT",
    "exemple": "• non cadre\n• cadre dirigeant non standard\n• statut RC personnalisé de l'entreprise",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Statut RC absent ou invalide",
    "codeInes": "INES_IJSS_ERR-2-40003-001",
    "familleInes": "Paie",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-40003-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40003",
    "nom": "StatutRC_Libelle",
    "description": "Libellé incohérent avec le contrat",
    "causePossible": "• Statut mal associé au type de contrat\n• Erreur de saisie lors du changement de statut\n• Promotion cadre/non-cadre non répercutée sur le contrat\n• Mapping incorrect entre le statut RC et la nature du contrat",
    "solution": "• Vérifier le contrat et corriger le libellé\n• Harmoniser le statut RC avec le contrat de travail\n• Mettre à jour après une promotion ou un changement de poste\n• Corriger le mapping dans le SIRH",
    "responsable": "• Paie\n• RH",
    "exemple": "• non cadre avec CDD\n• cadre avec contrat d'apprentissage\n• non cadre pour un poste de direction",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Statut RC absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-40003-001",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-40003-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40003",
    "nom": "StatutRC_Libelle",
    "description": "Statut RC absent",
    "causePossible": "• Information de statut manquante\n• Champ oublié lors de la création du contrat\n• Non-report depuis le SIRH\n• Nouveau contrat en cours de paramétrage",
    "solution": "• Compléter le libellé de statut RC\n• Renseigner selon le contrat de travail\n• Vérifier avec le service RH le statut applicable\n• Mettre à jour avant la prochaine échéance DSN",
    "responsable": "• Paie\n• RH",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Statut RC absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-40003-002",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-2-40014-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40014",
    "nom": "ModaliteTemps_libelle",
    "description": "Modalité de temps invalide",
    "causePossible": "• Valeur étrangement libellée ou non standardisé\n• Pourcentage de temps de travail saisi de façon erronée\n• Libellé métier interne non conforme à la nomenclature DSN\n• Erreur de saisie dans le SIRH",
    "solution": "• Utiliser un libellé de modalité de temps DSN correct\n• Corriger le pourcentage selon la norme DSN (ex: temps plein, temps partiel X%)\n• Consulter la nomenclature DSN des modalités de temps\n• Corriger le mapping SIRH vers DSN",
    "responsable": "• Paie\n• SIRH/IT",
    "exemple": "• Temps 150%\n• Temps -20%\n• modalité 999%",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Modalité de temps invalide ou incohérente",
    "codeInes": "INES_IJSS_ERR-2-40014-001",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-40014-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40014",
    "nom": "ModaliteTemps_libelle",
    "description": "Modalité de temps incompatible",
    "causePossible": "• Temps partiel déclaré avec contrat à temps plein\n• Erreur de saisie du pourcentage de temps de travail\n• Changement de quotité de travail non répercuté sur le contrat\n• Confusion entre modalité de temps et taux d'activité réel",
    "solution": "• Corriger la modalité ou le statut du contrat\n• Harmoniser la modalité de temps avec le contrat de travail\n• Mettre à jour après un avenant de temps partiel\n• Vérifier la quotité réelle avec le service RH",
    "responsable": "• Paie\n• RH",
    "exemple": "• Temps plein avec 80%\n• Temps partiel 100%\n• Temps plein avec 50%",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Modalité de temps invalide ou incohérente",
    "codeInes": "INES_IJSS_WRN-2-40014-001",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-40014-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40014",
    "nom": "ModaliteTemps_libelle",
    "description": "Modalité temps absente",
    "causePossible": "• Champ non renseigné\n• Oubli de saisie lors de la création du contrat\n• Valeur non exportée depuis le SIRH\n• Champ non mappé dans le pipeline DSN\n• Modalité non applicable au type de contrat, laissée vide par erreur",
    "solution": "• Renseigner la modalité de temps\n• Vérifier le contrat de travail pour déterminer la modalité exacte\n• Corriger le mapping d'export SIRH vers DSN\n• Contacter le service RH pour compléter l'information\n• Mettre à jour le paramétrage du logiciel de paie",
    "responsable": "• Paie\n• RH\n• SIRH/IT",
    "exemple": "• (vide)\n• null\n• espace vide \" \"\n• champ non présent dans l'export",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Modalité de temps invalide ou incohérente",
    "codeInes": "INES_IJSS_WRN-2-40014-002",
    "familleInes": "Paie",
    "prioriteInes": "P3",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60001-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60001",
    "nom": "Motif_Libelle",
    "description": "Motif incohérent avec le code motif",
    "causePossible": "• Libellé et code ne correspondent pas\n• Mise à jour partielle lors d'une correction manuelle\n• Erreur de mapping entre code et libellé dans le pipeline\n• Copier-coller d'un ancien enregistrement",
    "solution": "• Aligner le libellé avec le code du motif\n• Recalculer le libellé à partir du code officiel\n• Corriger manuellement l'un des deux champs\n• Vérifier la table de correspondance code/libellé",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 01 - maladie / autre\n• 02 - accident du travail / maladie\n• 03 - maternité / paternité incohérent",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Motif d'arrêt absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60001-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Risque"
  },
  {
    "code": "WRN-2-60001-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60001",
    "nom": "Motif_Libelle",
    "description": "Motif absent pour arrêt déclaré",
    "causePossible": "• Information manquante\n• Champ oublié lors de la déclaration d'arrêt\n• Erreur d'extraction depuis le SIRH\n• Arrêt saisi en urgence sans motif renseigné",
    "solution": "• Compléter le motif de l'arrêt\n• Contacter le salarié ou le service médical pour obtenir le motif\n• Vérifier le justificatif d'arrêt de travail\n• Relancer l'extraction DSN après correction",
    "responsable": "• Paie\n• RH\n• Salarié",
    "exemple": "• (vide)\n• null\n• champ manquant dans l'export",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Motif d'arrêt absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60001-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Risque"
  },
  {
    "code": "ERR-1-60002-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60002",
    "nom": "DernierJour",
    "description": "Format de date invalide",
    "causePossible": "• Date mal formatée ou non valide\n• Inversion jour/mois lors de la saisie\n• Export dans un format de date non standard\n• Date calendaire impossible (ex: 31 février)\n• Séparateur de date incorrect",
    "solution": "• Standardiser le format de date\n• Corriger la date selon le format JJ/MM/AAAA\n• Vérifier le paramétrage régional du système source\n• Revalider la date auprès du service paie",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 21/13/2025\n• 31/02/2026\n• 2025-13-40\n• 00/00/0000",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Dernier jour travaillé absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60002-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-60002-003",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60002",
    "nom": "DernierJour",
    "description": "Dernier jour après la date de fin prévue",
    "causePossible": "• Incohérence chronologique\n• Prolongation d'arrêt non répercutée sur la date de fin prévue\n• Erreur de saisie sur l'une des deux dates\n• Mise à jour partielle du dossier arrêt",
    "solution": "• Vérifier et corriger les dates d'arrêt\n• Mettre à jour la date de fin prévisionnelle en cas de prolongation\n• Contrôler la cohérence avec le certificat médical\n• Recalculer les dates à partir des justificatifs",
    "responsable": "• Paie\n• RH",
    "exemple": "• 24/04/2026 > 22/05/2026\n• DernierJour=15/06/2026 FinPrevue=01/06/2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Dernier jour travaillé absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60002-003",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60002-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60002",
    "nom": "DernierJour",
    "description": "Dernier jour antérieur à la période déclarée",
    "causePossible": "• Date hors période de déclaration\n• Arrêt terminé avant le mois déclaré mais déclaré en retard\n• Erreur de report sur une mauvaise période DSN\n• Régularisation tardive d'un arrêt antérieur",
    "solution": "• Vérifier cohérence entre dates et mois déclarés\n• Rattacher la déclaration à la bonne période DSN\n• Effectuer une déclaration corrective sur la période concernée\n• Contrôler le motif du décalage avec le service paie",
    "responsable": "• Paie",
    "exemple": "• 21/09/2025\n• DernierJour=05/01/2026 pour Declaration.Mois=03/2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Dernier jour travaillé absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60002-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60002-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60002",
    "nom": "DernierJour",
    "description": "Dernier jour incompatible avec reprise",
    "causePossible": "• Reprise antérieure au dernier jour\n• Erreur de saisie sur la date de reprise\n• Double saisie non synchronisée entre dernier jour et reprise\n• Correction de l'une des dates sans mise à jour de l'autre",
    "solution": "• Ajuster la date de reprise ou le dernier jour\n• Vérifier la chronologie complète de l'arrêt\n• Corriger la date erronée dans le dossier salarié\n• Revalider les deux dates avec le justificatif médical",
    "responsable": "• Paie\n• RH",
    "exemple": "• DernierJour=24/04/2026 Reprise=23/04/2026\n• DernierJour=10/03/2026 Reprise=09/03/2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Dernier jour travaillé absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60002-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-60003-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60003",
    "nom": "DateFinPrevisionnelle",
    "description": "Format de date invalide",
    "causePossible": "• Date mal formatée\n• Date calendaire inexistante (ex: 30 février)\n• Erreur de saisie manuelle\n• Export avec un séparateur ou un format non conforme",
    "solution": "• Corriger le format de date\n• Standardiser la date selon le format attendu\n• Vérifier la date auprès du certificat médical\n• Corriger la source d'export si le problème est systématique",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 2026-02-30\n• 31/04/2026\n• 00/00/0000",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Date de fin prévisionnelle absente ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60003-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60003-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60003",
    "nom": "DateFinPrevisionnelle",
    "description": "Fin prévisionnelle trop éloignée",
    "causePossible": "• Durée d'arrêt suspecte\n• Erreur de saisie ajoutant une année supplémentaire\n• Arrêt de longue durée réel (longue maladie) mal catégorisé\n• Confusion entre date de fin prévisionnelle et date de reprise",
    "solution": "• Vérifier la cohérence médicale et contractuelle\n• Confirmer la durée avec le certificat médical\n• Reclasser l'arrêt en longue maladie si justifié\n• Corriger la date si erreur de saisie",
    "responsable": "• Paie\n• RH",
    "exemple": "• 31/12/2026\n• 01/01/2030",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Date de fin prévisionnelle absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60003-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60010-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60010",
    "nom": "RepriseDate",
    "description": "Date de reprise absente alors que reprise attendue",
    "causePossible": "• Reprise non renseignée\n• Salarié ayant repris le travail sans mise à jour du dossier\n• Champ oublié lors de la clôture de l'arrêt\n• Information non transmise par le service RH",
    "solution": "• Compléter la date de reprise si disponible\n• Contacter le salarié ou le manager pour confirmer la reprise\n• Mettre à jour le dossier arrêt dans le SIRH\n• Vérifier le pointage/présence pour déterminer la date réelle",
    "responsable": "• Paie\n• RH",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Date de reprise absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60010-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-60010-001",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60010",
    "nom": "RepriseDate",
    "description": "Format de date invalide",
    "causePossible": "• Date mal formatée\n• Date calendaire impossible (ex: 31 avril)\n• Erreur de saisie manuelle\n• Format d'export non standard",
    "solution": "• Standardiser le format de date\n• Corriger la date selon le format attendu\n• Vérifier auprès du salarié ou du manager la date exacte de reprise\n• Corriger la source d'export",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 2026-04-31\n• 31/06/2026\n• 00/00/0000",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Date de reprise absente ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60010-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-60010-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60010",
    "nom": "RepriseDate",
    "description": "Date de reprise antérieure au dernier jour",
    "causePossible": "• Chronologie invalide\n• Inversion des deux dates lors de la saisie\n• Erreur de report entre le dernier jour d'arrêt et la reprise\n• Mise à jour incomplète après prolongation",
    "solution": "• Corriger la date de reprise\n• Vérifier la chronologie complète de l'arrêt\n• Rectifier la date erronée avec le justificatif\n• Revalider les deux dates avec le service RH",
    "responsable": "• Paie\n• RH",
    "exemple": "• Reprise=23/04/2026 DernierJour=24/04/2026\n• Reprise=01/03/2026 DernierJour=05/03/2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Date de reprise absente ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60010-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60010-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60010",
    "nom": "RepriseDate",
    "description": "Reprise après fin de contrat",
    "causePossible": "• Incohérence avec contrat\n• Contrat non renouvelé alors qu'une reprise est déclarée\n• Erreur de saisie sur la date de fin de contrat\n• Reprise déclarée sur un mauvais salarié/contrat",
    "solution": "• Vérifier la durée contractuelle\n• Confirmer si le contrat a été renouvelé ou prolongé\n• Corriger la date de reprise ou la date de fin de contrat\n• Rapprocher avec le service RH pour clarifier la situation contractuelle",
    "responsable": "• Paie\n• RH",
    "exemple": "• Reprise=01/01/2027\n• Reprise=15/09/2026 pour contrat terminé le 30/06/2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Date de reprise absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60010-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-2-99003-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99003",
    "nom": "Flag_rémunéré",
    "description": "Valeur de flag_rémunéré invalide",
    "causePossible": "• Non vrai/faux ou valeurs mal formées\n• Valeur textuelle non standardisée issue du SIRH\n• Erreur de conversion dans le pipeline Python\n• Champ mal typé lors de l'extraction",
    "solution": "• Standardiser en true/false\n• Corriger la fonction de conversion dans le pipeline Python\n• Mapper les valeurs sources vers un booléen valide\n• Revalider la donnée source",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• Oui\n• 1/0 mal interprété\n• \"Vrai\"\n• O/N",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Flag rémunéré invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-2-99003-001",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99003-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99003",
    "nom": "Flag_rémunéré",
    "description": "Flag absent ou vide",
    "causePossible": "• Information de rémunération non reportée\n• Champ non calculé par le pipeline pour ce cas\n• Absence de règle de gestion pour ce type d'arrêt\n• Donnée manquante en amont dans la paie",
    "solution": "• Compléter le flag rémunéré\n• Déterminer la rémunération réelle à partir du bulletin de paie\n• Ajouter une règle de calcul dans le pipeline Python\n• Vérifier la source de la donnée manquante",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 3,
    "anomalieInes": "Flag rémunéré invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-99003-001",
    "familleInes": "Paie",
    "prioriteInes": "P3",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99003-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99003",
    "nom": "Flag_rémunéré",
    "description": "Rémunération incohérente avec statut arrêt",
    "causePossible": "• Indication de rémunération divergente\n• Erreur de calcul dans le pipeline de reconstitution\n• Statut de l'arrêt mis à jour sans recalcul du flag\n• Incohérence entre le bulletin de paie et la déclaration d'arrêt",
    "solution": "• Vérifier le statut de l'arrêt et la paie\n• Recalculer le flag à partir des données de paie à jour\n• Corriger manuellement l'incohérence après vérification\n• Aligner la règle de calcul du pipeline avec le statut réel",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• true mais arrêt non rémunéré\n• false alors que le bulletin indique un maintien de salaire",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Flag rémunéré invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-99003-002",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-2-99004-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99004",
    "nom": "flag_annulation_G2SA",
    "description": "Valeur de flag_annulation_G2SA invalide",
    "causePossible": "• Valeur hors true/false\n• Format de valeur non standardisé en provenance de G2SA\n• Erreur de conversion dans le pipeline Python\n• Champ mal typé lors de l'extraction",
    "solution": "• Corriger le format du flag\n• Standardiser la conversion en booléen dans le pipeline\n• Mapper les valeurs sources vers true/false\n• Vérifier la donnée source dans G2SA",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• Yes\n• \"Vrai\"\n• 1/0 mal interprété",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Flag annulation absent ou invalide",
    "codeInes": "INES_IJSS_ERR-2-99004-001",
    "familleInes": "Cas complexes",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99004-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99004",
    "nom": "flag_annulation_G2SA",
    "description": "Flag absent",
    "causePossible": "• Indication d'annulation manquante\n• Champ non renseigné dans G2SA\n• Erreur d'extraction ou de mapping dans le pipeline\n• Valeur par défaut non définie",
    "solution": "• Compléter le flag d'annulation si nécessaire\n• Vérifier dans G2SA si l'arrêt a été annulé\n• Ajouter une valeur par défaut dans le pipeline\n• Contrôler la source d'extraction",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 3,
    "anomalieInes": "Flag annulation absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-99004-001",
    "familleInes": "Cas complexes",
    "prioriteInes": "P3",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99004-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99004",
    "nom": "flag_annulation_G2SA",
    "description": "Annulation marquée sans motif",
    "causePossible": "• Signalement incomplet\n• Annulation effectuée dans G2SA sans documentation du motif\n• Champ motif non repris par le pipeline\n• Oubli de saisie du motif d'annulation",
    "solution": "• Vérifier le motif d'annulation\n• Compléter le motif dans G2SA\n• Contacter le gestionnaire ayant réalisé l'annulation\n• Ajouter une contrainte de saisie obligatoire du motif dans G2SA",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• true sans raison\n• annulation=true, motif=null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Flag annulation absent ou invalide",
    "codeInes": "INES_IJSS_WRN-2-99004-002",
    "familleInes": "Cas complexes",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99005-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99005",
    "nom": "Nom usuel de la société",
    "description": "Nom société incohérent avec SIREN",
    "causePossible": "• Nom qui ne correspond pas à l'entreprise déclarée\n• Changement de raison sociale non répercuté\n• Erreur de saisie du nom d'entreprise\n• SIREN erroné associé à un autre nom",
    "solution": "• Vérifier avec le répertoire Sirene\n• Mettre à jour la raison sociale dans le référentiel\n• Corriger le SIREN ou le nom selon le cas erroné\n• Contrôler l'historique des changements de raison sociale",
    "responsable": "• Paie\n• Service juridique",
    "exemple": "• GRAND EST vs autre\n• SAS GRAND EST vs GROUPE GRAND EST SARL",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Nom usuel de la société incohérent ou mal formaté",
    "codeInes": "INES_IJSS_WRN-2-99005-001",
    "familleInes": "DSN",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99005-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99005",
    "nom": "Nom usuel de la société",
    "description": "Nom société mal formaté",
    "causePossible": "• Majuscules/espaces/caractères non standard\n• Espaces multiples issus de l'export\n• Caractères spéciaux non nettoyés\n• Casse incohérente (majuscules/minuscules mélangées)",
    "solution": "• Normaliser le libellé\n• Nettoyer les espaces superflus\n• Uniformiser la casse du nom de société\n• Ajouter une règle de normalisation dans le pipeline",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• GRAND EST\n• grand est\n• GRAND   EST",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 3,
    "anomalieInes": "Nom usuel de la société incohérent ou mal formaté",
    "codeInes": "INES_IJSS_WRN-2-99005-002",
    "familleInes": "DSN",
    "prioriteInes": "P3",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99006-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99006",
    "nom": "Nom usuel de l’établissement",
    "description": "Nom établissement incohérent avec NIC",
    "causePossible": "• Référentiel établi différent du nom déclaré\n• Établissement rattaché à un mauvais NIC\n• Changement d'enseigne non répercuté\n• Erreur de saisie du nom d'établissement",
    "solution": "• Vérifier avec le dossier établissement\n• Mettre à jour le référentiel établissement\n• Corriger le NIC ou le nom selon le cas erroné\n• Contrôler la fiche SIRENE de l'établissement",
    "responsable": "• Paie\n• RH",
    "exemple": "• GRAND EST / filiale\n• Établissement Paris vs NIC de l'établissement Lyon",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Nom usuel de l'établissement incohérent ou mal formaté",
    "codeInes": "INES_IJSS_WRN-2-99006-001",
    "familleInes": "DSN",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99006-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99006",
    "nom": "Nom usuel de l’établissement",
    "description": "Nom établissement mal formaté",
    "causePossible": "• Espaces ou ponctuation non standard\n• Casse incohérente (majuscules/minuscules mélangées)\n• Erreur de saisie dans le SIRH\n• Troncature du libellé lors de l'export DSN\n• Caractères spéciaux mal encodés (accents, apostrophes)",
    "solution": "• Nettoyer le libellé\n• Normaliser la casse\n• Supprimer les espaces multiples ou en début/fin de chaîne\n• Corriger l'encodage des caractères spéciaux\n• Mettre à jour le libellé dans le référentiel établissement",
    "responsable": "• Paie\n• SIRH/IT\n• RH\n• G2S Cortex",
    "exemple": "• GRAND  EST\n• grand est\n• GRAND-EST\n• GRAND EST;\n• GRAND ESTé",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 3,
    "anomalieInes": "Nom usuel de l'établissement incohérent ou mal formaté",
    "codeInes": "INES_IJSS_WRN-2-99006-002",
    "familleInes": "DSN",
    "prioriteInes": "P3",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "ERR-1-06001-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "6001",
    "nom": "Siren",
    "description": "SIREN non numérique",
    "causePossible": "• Présence de lettres ou caractères spéciaux\n• Erreur de saisie manuelle dans le SIRH\n• Export DSN corrompu ou mal formaté\n• Copier-coller depuis un document contenant des caractères invisibles\n• Confusion avec un autre identifiant (SIRET, RCS)",
    "solution": "• Rentrer un SIREN purement numérique\n• Supprimer les caractères non numériques\n• Vérifier le SIREN sur le Kbis ou via l'INSEE\n• Corriger le mapping d'export SIRH vers DSN",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• 54850A469\n• 548 501 469\n• SIREN548501469\n• 54850-1469",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "SIREN absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-06001-002",
    "familleInes": "Recouvrement",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-06001-003",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "6001",
    "nom": "Siren",
    "description": "SIREN longueur incorrecte",
    "causePossible": "• SIREN doit contenir 9 chiffres\n• Troncature lors de l'export\n• Saisie incomplète\n• Concaténation erronée avec le NIC (SIRET complet saisi par erreur)\n• Suppression accidentelle d'un chiffre",
    "solution": "• Corriger le nombre de chiffres\n• Compléter avec les chiffres manquants depuis le Kbis\n• Séparer le SIREN du NIC si SIRET saisi par erreur\n• Vérifier auprès de l'INSEE",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• 54850146\n• 5485014690\n• 548501\n• 54850146900",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "SIREN absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-06001-003",
    "familleInes": "Recouvrement",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-2-06001-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "6001",
    "nom": "Siren",
    "description": "SIREN invalide",
    "causePossible": "• Clé de contrôle incorrecte\n• Inversion de chiffres lors de la saisie\n• SIREN d'une entreprise radiée/fermée\n• Erreur de transcription depuis un document papier\n• Numéro fictif ou de test resté en production",
    "solution": "• Vérifier le numéro SIREN auprès de l'INSEE\n• Corriger la clé de contrôle\n• Mettre à jour avec le SIREN officiel Sirene\n• Contacter le service juridique/RH pour confirmation",
    "responsable": "• Paie\n• Service juridique\n• G2S Cortex",
    "exemple": "• 548501460\n• 123456789\n• 000000000\n• 548501461",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "SIREN absent ou invalide",
    "codeInes": "INES_IJSS_ERR-2-06001-001",
    "familleInes": "Recouvrement",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-06001-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "6001",
    "nom": "Siren",
    "description": "SIREN incohérent avec le nom société",
    "causePossible": "• Correspondance entreprise/SIREN douteuse\n• Changement de raison sociale non répercuté\n• Fusion/absorption d'entreprise non mise à jour\n• Erreur de rattachement d'établissement dans le SIRH",
    "solution": "• Contrôler l'association entreprise/SIREN\n• Mettre à jour le nom de société dans le référentiel\n• Vérifier via l'annuaire Sirene\n• Corriger le rattachement établissement/société",
    "responsable": "• Paie\n• Service juridique\n• SIRH/IT",
    "exemple": "• 548501469 / autre société\n• SIREN d'une filiale utilisé pour la maison mère\n• SIREN ancien après fusion",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "SIREN incohérent avec le nom de la société",
    "codeInes": "INES_IJSS_WRN-2-06001-001",
    "familleInes": "Recouvrement",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-11001-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "11001",
    "nom": "Nic",
    "description": "NIC non numérique",
    "causePossible": "• Valeur invalide sur le NIC\n• Présence de lettres ou symboles\n• Erreur de saisie manuelle\n• Copier-coller avec caractères invisibles\n• Confusion avec un autre champ",
    "solution": "• Corriger en chiffres\n• Supprimer les caractères non numériques\n• Vérifier le NIC dans le référentiel établissement\n• Corriger le mapping d'export",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• 0004A\n• NIC004\n• 00-04\n• 4A56",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIC absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-11001-002",
    "familleInes": "Recouvrement",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-11001-003",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "11001",
    "nom": "Nic",
    "description": "NIC longueur incorrecte",
    "causePossible": "• NIC doit contenir 5 chiffres\n• Troncature des zéros de tête lors de l'export\n• Saisie incomplète\n• Confusion avec un numéro à 4 chiffres",
    "solution": "• Corriger le nombre de chiffres\n• Réintégrer les zéros de tête\n• Vérifier le NIC dans le référentiel établissement\n• Compléter avec le SIRET officiel",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• 41\n• 004\n• 00041000\n• 4100",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "NIC absent ou invalide",
    "codeInes": "INES_IJSS_ERR-1-11001-003",
    "familleInes": "Recouvrement",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-11001-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "11001",
    "nom": "Nic",
    "description": "NIC incohérent avec SIREN",
    "causePossible": "• Établissement mal référencé\n• Mauvais rattachement établissement/société\n• Changement d'établissement non répercuté\n• Erreur de mapping SIRET (SIREN+NIC)",
    "solution": "• Vérifier le numéro NIC et le SIRET complet\n• Corriger le rattachement dans le référentiel établissement\n• Vérifier via l'INSEE/Sirene\n• Recomposer le SIRET correct",
    "responsable": "• Paie\n• SIRH/IT\n• Service juridique",
    "exemple": "• 00042 incorrect\n• NIC d'un autre établissement du groupe\n• SIRET recomposé invalide",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "NIC incohérent avec le SIREN",
    "codeInes": "INES_IJSS_WRN-2-11001-001",
    "familleInes": "Recouvrement",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-2-30005-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30005",
    "nom": "Sexe",
    "description": "Sexe invalide",
    "causePossible": "• Valeur non reconnue par la DSN\n• Erreur de saisie dans le SIRH\n• Valeur issue d'un système tiers non mappée\n• Champ vide converti en valeur par défaut erronée",
    "solution": "• Utiliser le libellé ou code standard\n• Corriger avec la valeur 01 (Masculin) ou 02 (Féminin)\n• Vérifier la pièce d'identité du salarié\n• Corriger le mapping SIRH vers DSN",
    "responsable": "• RH\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• Inconnu\n• X\n• 0\n• Non précisé\n• N/A",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Prénom ou sexe invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-2-30005-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-30005-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "30005",
    "nom": "Sexe",
    "description": "Sexe incohérent avec Prénom/nom civil",
    "causePossible": "• Suspicion d'erreur de saisie\n• Prénom mixte/épicène rendant l'incohérence apparente mais non réelle\n• Inversion des champs sexe/civilité\n• Changement de sexe à l'état civil non mis à jour",
    "solution": "• Vérifier la fiche salarié\n• Confirmer via la pièce d'identité\n• Corriger le champ sexe ou le prénom selon le cas\n• Ne pas modifier si prénom mixte légitime après vérification",
    "responsable": "• RH\n• Salarié",
    "exemple": "• Féminin pour prénom masculin\n• Masculin pour prénom Camille\n• Sexe Masculin avec civilité Mme",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Prénom ou sexe invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-30005-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "ERR-2-40004-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40004",
    "nom": "PcsEse",
    "description": "PCS-ESE invalide",
    "causePossible": "• Code métier non conforme\n• Code obsolète non reconnu par la nomenclature en vigueur\n• Erreur de saisie ou de mapping SIRH\n• Code d'une autre nomenclature (PCS INSEE vs PCS-ESE)",
    "solution": "• Utiliser un code PCS-ESE valide\n• Consulter la table de correspondance PCS-ESE officielle\n• Corriger le mapping SIRH vers DSN\n• Mettre à jour le référentiel métier",
    "responsable": "• Paie\n• RH\n• SIRH/IT",
    "exemple": "• 999999\n• 0000\n• ABCD\n• code PCS INSEE utilisé au lieu de PCS-ESE",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_ERR-2-40004-001",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-40004-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40004",
    "nom": "PcsEse",
    "description": "PCS-ESE absent",
    "causePossible": "• Métier non renseigné\n• Champ oublié à l'embauche\n• Non-report lors de la migration SIRH\n• Poste nouvellement créé sans code associé",
    "solution": "• Compléter le code PCS-ESE\n• Renseigner selon la fiche de poste\n• Vérifier avec le service RH\n• Mettre à jour lors de la prochaine paie",
    "responsable": "• Paie\n• RH",
    "exemple": "• (vide)\n• 00000",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_WRN-2-40004-001",
    "familleInes": "Salarié",
    "prioriteInes": "P3",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-40004-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40004",
    "nom": "PcsEse",
    "description": "PCS-ESE obsolète ou non standard",
    "causePossible": "• Code métier ancien\n• Nomenclature PCS-ESE non mise à jour dans le SIRH\n• Reprise de données historiques non actualisées",
    "solution": "• Mettre à jour vers un code actuel\n• Consulter la nomenclature PCS-ESE en vigueur\n• Actualiser le référentiel métier du SIRH",
    "responsable": "• Paie\n• RH\n• SIRH/IT",
    "exemple": "• Femme de Ménage invalidé\n• code PCS-ESE version 2003\n• intitulé métier disparu de la nomenclature",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_WRN-2-40004-002",
    "familleInes": "Salarié",
    "prioriteInes": "P2",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-40006-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40006",
    "nom": "LibelleEmploi",
    "description": "Libellé emploi trop générique",
    "causePossible": "• Information insuffisante\n• Champ rempli par défaut lors de la création de la fiche\n• Absence de fiche de poste détaillée\n• Simplification volontaire par le gestionnaire paie",
    "solution": "• Préciser le poste ou la fonction\n• Compléter avec l'intitulé de poste exact\n• Se référer au contrat de travail\n• Harmoniser avec la fiche de poste RH",
    "responsable": "• Paie\n• RH",
    "exemple": "• Personnel\n• Employé\n• Salarié\n• Divers",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Matricule ou classification salarié invalide",
    "codeInes": "INES_IJSS_WRN-2-40006-001",
    "familleInes": "Salarié",
    "prioriteInes": "P3",
    "dimensionInes": "Salarié"
  },
  {
    "code": "WRN-2-40007-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40007",
    "nom": "Nature",
    "description": "Nature du contrat incohérente avec le libellé",
    "causePossible": "• Incohérence code/libellé\n• Erreur de saisie du code contrat\n• Mapping incorrect entre le SIRH et la nomenclature DSN\n• Changement de contrat non répercuté sur le code",
    "solution": "• Harmoniser la nature et son libellé\n• Corriger le code contrat selon le libellé réel\n• Vérifier le contrat de travail signé\n• Corriger le mapping SIRH vers DSN",
    "responsable": "• Paie\n• RH\n• SIRH/IT",
    "exemple": "• CDI avec nature apprentissage\n• CDD avec code CDI\n• Contrat de professionnalisation avec code CDI",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nature du contrat incohérente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-40007-002",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "ERR-2-40007-002",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40007",
    "nom": "Nature_libelle",
    "description": "Libellé nature invalide",
    "causePossible": "• Libellé non reconnu\n• Libellé saisi manuellement au lieu d'être sélectionné dans la liste\n• Ancienne nomenclature de libellés non mise à jour\n• Erreur d'export du pipeline Python",
    "solution": "• Utiliser le libellé DSN correct\n• Consulter la liste des libellés DSN normés\n• Corriger le mapping code vers libellé\n• Mettre à jour le référentiel des natures de contrat",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• Contrat de travail à durée indéterminée de droit privé\n• CDI simple\n• Contrat classique",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nature du contrat incohérente ou invalide",
    "codeInes": "INES_IJSS_ERR-2-40007-002",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40007-003",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40007",
    "nom": "Nature_libelle",
    "description": "Libellé nature incohérent avec le code",
    "causePossible": "• Code/libellé en désaccord\n• Mise à jour partielle lors d'un changement de contrat\n• Erreur de saisie manuelle du libellé\n• Mapping code-libellé obsolète",
    "solution": "• Harmoniser code et libellé\n• Corriger le libellé selon le code réel\n• Vérifier le contrat de travail\n• Mettre à jour la table de correspondance code/libellé",
    "responsable": "• Paie\n• SIRH/IT",
    "exemple": "• CDD avec libellé CDI\n• Code apprentissage avec libellé CDI\n• Code CDI avec libellé stage",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Nature du contrat incohérente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-40007-003",
    "familleInes": "Paie",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40007-004",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40007",
    "nom": "Nature_libelle",
    "description": "Libellé nature trop long ou mal formaté",
    "causePossible": "• Valeur mal normalisée\n• Concaténation de plusieurs libellés\n• Espaces ou caractères parasites\n• Export tronqué ou dupliqué depuis le SIRH",
    "solution": "• Standardiser le libellé\n• Tronquer/nettoyer selon la norme DSN\n• Utiliser le libellé officiel court\n• Corriger le pipeline d'export",
    "responsable": "• Paie\n• SIRH/IT\n• G2S Cortex",
    "exemple": "• Contrat de travail ...\n• Contrat de travail à durée indéterminée de droit privé - Temps plein - Cadre\n• CDI  CDI",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Nature du contrat incohérente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-40007-004",
    "familleInes": "Paie",
    "prioriteInes": "P3",
    "dimensionInes": "Charges"
  },
  {
    "code": "ERR-2-40008-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique",
    "description": "Dispositif politique invalide",
    "causePossible": "• Code non reconnu\n• Code obsolète suite à une réforme des dispositifs d'aide à l'emploi\n• Erreur de saisie\n• Mapping SIRH vers DSN incorrect",
    "solution": "• Utiliser un code valide\n• Consulter la nomenclature des dispositifs en vigueur\n• Corriger le mapping d'export\n• Vérifier avec le service RH le dispositif réellement appliqué",
    "responsable": "• Paie\n• RH\n• SIRH/IT",
    "exemple": "• XYZ\n• 99 (code inexistant)\n• code dispositif abrogé",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Dispositif politique invalide ou absent",
    "codeInes": "INES_IJSS_ERR-2-40008-001",
    "familleInes": "Charges sociales",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40008-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique",
    "description": "Dispositif absent alors qu’il est attendu",
    "causePossible": "• Champ manquant\n• Oubli lors de la création du contrat aidé\n• Non-report depuis le SIRH\n• Erreur du pipeline d'extraction",
    "solution": "• Compléter le dispositif politique\n• Vérifier le contrat pour identifier le dispositif applicable\n• Renseigner Non concerné si aucun dispositif ne s'applique\n• Corriger l'extraction",
    "responsable": "• Paie\n• RH\n• G2S Cortex",
    "exemple": "• (vide)",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Dispositif politique invalide ou absent",
    "codeInes": "INES_IJSS_WRN-2-40008-001",
    "familleInes": "Charges sociales",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40008-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique",
    "description": "Dispositif incohérent avec la nature du contrat",
    "causePossible": "• Code/dispositif mal apparié\n• Dispositif renseigné pour un type de contrat qui n'y est pas éligible\n• Erreur de saisie lors du renouvellement de contrat\n• Changement de contrat sans mise à jour du dispositif",
    "solution": "• Vérifier l'application du dispositif politique\n• Corriger le dispositif selon l'éligibilité réelle\n• Consulter les règles d'éligibilité du dispositif\n• Mettre à jour après renouvellement de contrat",
    "responsable": "• Paie\n• RH",
    "exemple": "• Non Concerné avec contrat particulier\n• Dispositif apprentissage sur un CDI classique\n• Contrat aidé sans dispositif correspondant",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Dispositif politique invalide ou absent",
    "codeInes": "INES_IJSS_WRN-2-40008-002",
    "familleInes": "Charges sociales",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "ERR-2-40008-002",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique_Libelle",
    "description": "Libellé dispositif invalide",
    "causePossible": "• Libellé non reconnu\n• Faute de frappe dans le libellé\n• Libellé issu d'une ancienne nomenclature\n• Mapping code vers libellé incorrect",
    "solution": "• Utiliser un libellé DSN valide\n• Corriger la faute de frappe\n• Mettre à jour la table de correspondance\n• Consulter la nomenclature officielle des dispositifs",
    "responsable": "• Paie\n• SIRH/IT",
    "exemple": "• Non concernéee\n• Non concerner\n• dispositif inconnu",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Libellé dispositif politique invalide ou incohérent",
    "codeInes": "INES_IJSS_ERR-2-40008-002",
    "familleInes": "Charges sociales",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40008-003",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique_Libelle",
    "description": "Libellé dispositif incohérent avec le code",
    "causePossible": "• Code/libellé mal appariés\n• Mise à jour partielle du dispositif\n• Erreur de mapping code vers libellé\n• Libellé resté inchangé après changement de code",
    "solution": "• Harmoniser le code et le libellé\n• Corriger le libellé selon le code réel\n• Mettre à jour la table de correspondance code/libellé\n• Vérifier le dispositif appliqué au contrat",
    "responsable": "• Paie\n• SIRH/IT",
    "exemple": "• Non Concerné / Contrat d'apprentissage\n• Code Non Concerné avec libellé Aide à l'embauche\n• Code dispositif X avec libellé dispositif Y",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Libellé dispositif politique invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-40008-003",
    "familleInes": "Charges sociales",
    "prioriteInes": "P2",
    "dimensionInes": "Charges"
  },
  {
    "code": "WRN-2-40008-004",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "40008",
    "nom": "DispositifPolitique_Libelle",
    "description": "Libellé dispositif absent",
    "causePossible": "• Libellé non renseigné\n• Champ omis lors de la saisie dans le SIRH\n• Absence de mapping entre le code dispositif et son libellé dans l'export DSN\n• Dispositif politique non applicable mais champ laissé vide au lieu d'indiquer 'Non concerné'\n• Bug du pipeline d'extraction Python qui ne récupère pas le libellé",
    "solution": "• Compléter le libellé du dispositif politique\n• Renseigner 'Non concerné' si aucun dispositif ne s'applique\n• Vérifier le paramétrage du dispositif dans le logiciel de paie\n• Corriger le mapping code/libellé dans le pipeline d'export",
    "responsable": "• Paie\n• RH\n• G2S Cortex",
    "exemple": "• (vide)\n• null\n• chaîne vide \"\"\n• espace uniquement \" \"",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 3,
    "anomalieInes": "Libellé dispositif politique invalide ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-40008-004",
    "familleInes": "Charges sociales",
    "prioriteInes": "P3",
    "dimensionInes": "Charges"
  },
  {
    "code": "ERR-2-60001-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60001",
    "nom": "Motif",
    "description": "Code de motif invalide",
    "causePossible": "• Code motif non reconnu\n• Code motif obsolète (ancienne nomenclature DSN)\n• Erreur de saisie du code motif dans le SIRH\n• Code motif tronqué ou mal exporté par le pipeline\n• Motif propre au logiciel de paie non mappé vers la norme DSN",
    "solution": "• Utiliser un code DSN valide\n• Se référer à la table de correspondance des motifs DSN en vigueur\n• Corriger la saisie du motif dans le dossier salarié\n• Mettre à jour le mapping des motifs dans le pipeline d'extraction",
    "responsable": "• Paie\n• RH\n• G2S Cortex",
    "exemple": "• 15\n• 00\n• 99\n• XX\n• AT (au lieu d'un code numérique)",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Motif d'arrêt absent ou invalide",
    "codeInes": "INES_IJSS_ERR-2-60001-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Risque"
  },
  {
    "code": "ALT-2-60001-002",
    "type": "ALT",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60001",
    "nom": "Motif",
    "description": "Chevauchement des motifs d'arrêt",
    "causePossible": "• Un salarié est en arrêt pour 2 motifs, les 2 arrêts commencent la même période mais pas la même date de fin\n• Prolongation d'arrêt déclarée comme un nouvel arrêt distinct au lieu d'être fusionnée\n• Rechute déclarée en doublon avec l'arrêt initial non clôturé\n• Bug du pipeline Python ne détectant pas la fusion de deux arrêts contigus\n• Ressaisie manuelle d'un arrêt déjà existant avec un motif différent",
    "solution": "• Mise à jour du code Python pour fusionner/dédupliquer les arrêts chevauchants\n• Vérifier manuellement les dates de chaque arrêt et clôturer le doublon\n• Contacter la paie pour confirmer le motif et la date de fin réelle\n• Ajouter une règle de détection de chevauchement dans le pipeline d'extraction",
    "responsable": "• G2S Cortex\n• Paie\n• RH",
    "exemple": "• null\n• Arrêt maladie du 01/03/2026 au 15/03/2026 et arrêt AT du 01/03/2026 au 20/03/2026\n• Deux arrêts avec même date de début mais motifs 'maladie' et 'accident du travail'",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 10,
    "anomalieInes": "Motif d'arrêt absent ou invalide",
    "codeInes": "INES_IJSS_ALT-2-60001-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Risque"
  },
  {
    "code": "ERR-2-60004-001",
    "type": "ERR",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60004",
    "nom": "Subrogation",
    "description": "Subrogation invalide",
    "causePossible": "• Valeur non reconnue\n• Erreur de saisie du code subrogation\n• Format de valeur non conforme à la norme DSN (attendu O/N)\n• Valeur héritée d'un ancien système de paie non convertie",
    "solution": "• Utiliser un code / libellé valide\n• Standardiser en oui/non selon la norme DSN\n• Corriger la saisie dans le logiciel de paie",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 2-Non\n• Oui/Non mal formaté\n• 1\n• true/false au lieu de oui/non",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Subrogation absente ou invalide",
    "codeInes": "INES_IJSS_ERR-2-60004-001",
    "familleInes": "Subrogation",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60004-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60004",
    "nom": "Subrogation",
    "description": "Subrogation manquante pour arrêt indemnisé",
    "causePossible": "• Information partielle\n• Champ subrogation non renseigné lors de la déclaration\n• Oubli de la mention subrogation employeur\n• Pipeline d'extraction ne récupérant pas cette information",
    "solution": "• Compléter la subrogation\n• Vérifier auprès de la paie si l'employeur est subrogé\n• Renseigner le champ manquant avant réémission de la DSN",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Subrogation absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60004-001",
    "familleInes": "Subrogation",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60004-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60004",
    "nom": "Subrogation",
    "description": "Subrogation incohérente avec statut RC",
    "causePossible": "• Subrogation incompatible avec indemnisation\n• Statut RC mis à jour sans répercussion sur la subrogation\n• Erreur de saisie croisée entre deux champs liés\n• Changement de régime de subrogation en cours de mois non reporté",
    "solution": "• Vérifier le régime de subrogation\n• Aligner la subrogation avec le statut RC réel\n• Contrôler la cohérence des deux champs avant validation",
    "responsable": "• Paie\n• RH",
    "exemple": "• Non alors que RC indique oui\n• Oui alors que RC indique non",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Subrogation absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60004-002",
    "familleInes": "Subrogation",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-60012-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "60012",
    "nom": "DateAccident",
    "description": "Date d’accident absente pour accident de trajet",
    "causePossible": "• Champ attendu selon le motif\n• Oubli de saisie de la date d'accident\n• Motif 'accident' saisi sans les informations complémentaires associées\n• Information non transmise par le salarié ou l'employeur",
    "solution": "• Vérifier l'absence d'accident et compléter le cas échéant\n• Demander la date d'accident au salarié ou au service concerné\n• Compléter la déclaration avant transmission DSN",
    "responsable": "• Paie\n• RH",
    "exemple": "• (vide)\n• null",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Date d'accident absente ou invalide",
    "codeInes": "INES_IJSS_WRN-2-60012-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Risque"
  },
  {
    "code": "ERR-1-60012-001",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "60012",
    "nom": "DateAccident",
    "description": "Format date accident invalide",
    "causePossible": "• Date mal formatée\n• Date impossible (ex: 30 février)\n• Inversion jour/mois lors de la saisie\n• Erreur d'export du pipeline sur le format de date",
    "solution": "• Standardiser la date accident\n• Corriger la date selon le format JJ/MM/AAAA\n• Vérifier la date auprès du dossier accident du travail",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 2026-02-30\n• 31/04/2026\n• 00/00/0000",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "scoreMax": 6,
    "anomalieInes": "Date d'accident absente ou invalide",
    "codeInes": "INES_IJSS_ERR-1-60012-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Risque"
  },
  {
    "code": "WRN-2-99008-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99008",
    "nom": "Ville de la société",
    "description": "Ville incohérente avec le SIREN",
    "causePossible": "• Localisation invalide\n• Établissement ayant déménagé sans mise à jour du référentiel\n• Erreur de mapping entre SIREN et adresse dans le pipeline Python\n• Confusion entre siège social et établissement secondaire",
    "solution": "• Vérifier l'adresse établissement\n• Mettre à jour le référentiel SIRENE/établissement\n• Corriger le mapping dans le pipeline d'extraction",
    "responsable": "• Paie\n• G2S Cortex\n• RH",
    "exemple": "• GRAND EST\n• Paris au lieu de Strasbourg\n• ville d'un autre établissement du groupe",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Ville de la société incohérente ou mal formatée",
    "codeInes": "INES_IJSS_WRN-2-99008-001",
    "familleInes": "DSN",
    "prioriteInes": "P2",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "WRN-2-99008-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99008",
    "nom": "Ville de la société",
    "description": "Ville mal formatée",
    "causePossible": "• Caractères ou espaces non normaux\n• Espaces multiples ou en fin de chaîne\n• Casse incohérente (majuscules/minuscules)\n• Caractères spéciaux issus d'un export non nettoyé",
    "solution": "• Normaliser le libellé de ville\n• Supprimer les espaces superflus\n• Uniformiser la casse",
    "responsable": "• G2S Cortex\n• Paie",
    "exemple": "• Paris\n• Strasbourg\n• PARIS123\n• Paris/",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Basse",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 3,
    "anomalieInes": "Ville de la société incohérente ou mal formatée",
    "codeInes": "INES_IJSS_WRN-2-99008-002",
    "familleInes": "DSN",
    "prioriteInes": "P3",
    "dimensionInes": "Pilotage"
  },
  {
    "code": "ERR-1-99009-003",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "99009",
    "nom": "Nb_jours_absences_SS",
    "description": "Nombre de jours non entier",
    "causePossible": "• Valeur décimale ou alphabétique\n• Erreur de calcul du pipeline Python (division non arrondie)\n• Saisie manuelle erronée avec virgule/point décimal\n• Export d'une valeur texte au lieu d'un nombre",
    "solution": "• Utiliser un entier\n• Arrondir ou recalculer le nombre de jours\n• Corriger le format du champ dans le pipeline",
    "responsable": "• G2S Cortex\n• Paie",
    "exemple": "• 15.5\n• quinze\n• 15,5\n• NaN",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 10,
    "anomalieInes": "Nombre de jours d'absence SS incorrect",
    "codeInes": "INES_IJSS_ERR-1-99009-003",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99009-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99009",
    "nom": "Nb_jours_absences_SS",
    "description": "Nombre de jours incohérent avec les dates",
    "causePossible": "• Calcul incompatible avec la période d'arrêt\n• Erreur dans le calcul du pipeline (jours calendaires vs ouvrés)\n• Dates d'arrêt modifiées sans recalcul du nombre de jours\n• Double comptage de jours lors d'une prolongation",
    "solution": "• Recalculer avec les dates effectives\n• Vérifier la formule de calcul du nombre de jours dans le pipeline\n• Corriger manuellement après vérification des dates",
    "responsable": "• G2S Cortex\n• Paie",
    "exemple": "• 31 pour 15 jours\n• 0 jour pour un arrêt d'un mois\n• jours négatifs",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Nombre de jours d'absence SS incorrect",
    "codeInes": "INES_IJSS_WRN-2-99009-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99009-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99009",
    "nom": "Nb_jours_absences_SS",
    "description": "Nombre de jours trop élevé",
    "causePossible": "• Valeur suspecte\n• Cumul erroné de plusieurs arrêts\n• Erreur de saisie (chiffre ajouté par erreur)\n• Absence de plafond de contrôle dans le pipeline",
    "solution": "• Vérifier le calcul de la durée\n• Comparer avec les dates de début et fin d'arrêt\n• Ajouter un contrôle de vraisemblance dans le pipeline",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 99\n• 365 jours pour un arrêt d'une semaine\n• 999",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Nombre de jours d'absence SS incorrect",
    "codeInes": "INES_IJSS_WRN-2-99009-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "ERR-1-99010-002",
    "type": "ERR",
    "categorie": "Saisie",
    "sousCategorieDsn": "99010",
    "nom": "mois_absence",
    "description": "Format mois_absence invalide",
    "causePossible": "• Valeur non normalisée\n• Format mois/année inversé\n• Absence du jour ou du siècle dans la date\n• Export du pipeline sans normalisation du format",
    "solution": "• Utiliser le format attendu\n• Normaliser au format MM/AAAA ou JJ/MM/AAAA selon la norme\n• Corriger le format dans le pipeline d'extraction",
    "responsable": "• G2S Cortex\n• Paie",
    "exemple": "• 1/2026\n• 2026-1\n• janvier 2026\n• 01-26",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Haute",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 10,
    "anomalieInes": "Mois d'absence incorrect ou incohérent",
    "codeInes": "INES_IJSS_ERR-1-99010-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P1",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99010-001",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99010",
    "nom": "mois_absence",
    "description": "mois_absence incompatible avec Declaration.Mois",
    "causePossible": "• Mois déclaré différent du mois d'absence\n• Arrêt à cheval sur deux mois déclaré sur le mauvais mois\n• Erreur de saisie du mois de déclaration\n• Décalage de traitement entre mois d'absence réel et mois de paie",
    "solution": "• Vérifier la période d'absence\n• Aligner le mois d'absence avec le mois de déclaration DSN\n• Corriger la déclaration si le décalage n'est pas justifié",
    "responsable": "• Paie\n• RH",
    "exemple": "• 01/01/2026 vs 01/04/2026\n• décembre 2025 déclaré en janvier 2026",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Mois d'absence incorrect ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-99010-001",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  },
  {
    "code": "WRN-2-99010-002",
    "type": "WRN",
    "categorie": "Paramétrique",
    "sousCategorieDsn": "99010",
    "nom": "mois_absence",
    "description": "mois_absence incohérent avec les dates d’arrêt",
    "causePossible": "• Période d'absence non alignée sur l'arrêt\n• Mois d'absence renseigné manuellement sans recalcul suite à modification des dates\n• Erreur de report d'un mois sur l'autre lors d'une prolongation\n• Bug du pipeline lors du calcul du mois d'absence",
    "solution": "• Corriger le mois d'absence\n• Recalculer le mois d'absence à partir des dates d'arrêt\n• Vérifier la cohérence entre dates d'arrêt et mois déclaré",
    "responsable": "• Paie\n• G2S Cortex",
    "exemple": "• 01/05/2026 pour arrêt terminé en 04/2026\n• mois d'absence antérieur à la date de début d'arrêt",
    "liens": "",
    "statut": "Non actif",
    "priorite": "Moyenne",
    "dateAjout": "2026-06-25 00:00:00",
    "derniereMiseAJour": "2026-06-25 00:00:00",
    "commentaireG2sCortex": "Note : Les sous catégorie 99xxx sont des rubriques qui ne sont pas issus de la DSN, mais sont des colonnes reconstituées grâce à un pipeline Python.",
    "scoreMax": 6,
    "anomalieInes": "Mois d'absence incorrect ou incohérent",
    "codeInes": "INES_IJSS_WRN-2-99010-002",
    "familleInes": "Calcul IJSS",
    "prioriteInes": "P2",
    "dimensionInes": "Financière"
  }
]